server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/jackrott/SpringCloudConfig-GitRepository
                    username: jackrott
                    password: Dirtyro1

    profiles:
        active: dev